[package]
name = "parol"
version = "0.6.0-pre"
authors = ["Jörg Singer <singer.joerg@gmx.de>"]
description = "LL(k) parser generator for Rust."
documentation = "https://docs.rs/parol"
repository = "https://github.com/jsinger67/parol"
readme = "README.md"
keywords = ["parser", "parsing", "parser-generator", "LLk"]
categories = ["algorithms", "parsing", "Parsing tools"]
license = "MIT"
edition = "2018"

[dependencies]
bart = "0.1.4"
bart_derive = "0.1.4"
clap = { version = "3.0.0", features = [ "derive", "cargo" ] }
env_logger = "0.9.0"
id_tree = "1.8.0"
id_tree_layout = "2.0.2"
lazy_static = "1.4.0"
log = "0.4.14"
miette = { version = "3.2.0", features = ["fancy"] }
parol_runtime = "0.5.4"
petgraph = "0.6.0"
rand_regex = "0.15.1"
rand = "0.8.4"
regex = "1.5.4"
regex-syntax = "0.6.25"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.69"
thiserror = "1.0.30"

[profile.release]
debug = true

[features]
default = ["build"]
# Includes logic for invoking from build.rs script
build = []

[[bin]]
name = "parol"
# Much of the logic formerly in the main binary has been refactored into the library
required-features = ["build"]
